### ISSUE TITLE
Flashing instructions for Pinecil incomplete

### ISSUE THREAD

**Issue by cybernesto** [Ralim/IronOS#1141]
**Describe the bug**
The IronOS/Documentation/Flashing.md document suggests following command for flashing a Pinecil:
`dfu-util -D Pinecil_EN.dfu`
 .dfu files were replaced by .bin files in the current stable version. Trying to flash a .bin file with this command does not work because dfu-util finds the option bytes as a separate alt-setting.

**To Reproduce**
```
dfu-util -D Pinecil_DE.bin
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Warning: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release
dfu-util: More than one DFU capable USB device found! Try `--list' and specify the serial number or disconnect all but one device
```

**Expected behavior**
The command for flashing a Pinecil should be instead:
`dfu-util -d 28e9:0189 -a 0 -D Pinecil_DE.bin -s 0x08000000`

the -s option is necessary for raw binary download. Otherwise the following message is displayed:

```
dfu-util: Only DfuSe file version 1.1a is supported
dfu-util: (for raw binary download, use the --dfuse-address option)
```

**Details on your device:**
 
 - Device: Pinecil
 - dfu-util Version: 0.11
 - OS
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

**Comment by Johnex** [comment]
It's the other way around. The latest RC is using DFU, and that will be the type used for the next stable version. The wiki was updated in preparation for that, and honestly you should be using the latest RC as it is considered stable, i have been using it for a few weeks now since it came out. It has a lot of PD fixes, menus work better and screen updates are faster.

**Comment by cybernesto** [comment]
Thanks for the clarification. Maybe a short notice stating that the DFU mode is only supported by the current RC would avoid issues. 

cybernesto

**Comment by Johnex** [comment]
@Ralim Is anything missing to push out a new stable release? The latest RC has been working amazing for me for a long time now.

**Comment by cybernesto** [comment]
I just tried the RC2: V2.16. Flashing worked as documented. Thanks for the hint. I have found one flaw though. With v2.15 I was able to use up to 12V in QC mode from my power supply. The RC2 only offers 5V. Changing the power settings does not help. Is this a known issue?

**Comment by Ralim** [comment]
@cybernesto 
Please create a new issue for issues with QC for your specific charger.
Make sure to include details on what firmware you were using before and  what model your charger is so that it can be checked if its QC3 or QC2 certified or not certified at all.

QC is NOT RECOMMENDED due to it being terribly implemented by different chargers, and only just meeting the minimum 12V voltage.

**Comment by Ralim** [comment]
Still some niggling issues to sort out in settings refactor and then ill be releasing it

**Comment by cybernesto** [comment]
Closing this issue since the flashing instructions refer to the dfu files included in the RC. A comment about this would be nice though.

**Comment by Ralim** [comment]
Intent is that you read the instructions that match the file you download.
You can click the version tag (starts with `v`) next to the release to view the data matching that release.

**Comment by cybernesto** [comment]
Brilliant. I was not aware of this feature. Thanks for the hint!
