### ISSUE TITLE
Since 2.17 the icons are not vertically centered

### ISSUE THREAD

**Issue by NiklasVoigt** [Ralim/IronOS#1252]
**Describe the bug**
Since 2.17 the icons are not vertically centered

**To Reproduce**

**Expected behavior**

**Details of your device:**
 
 - Device: TS100
 - Release: 2.17
 - Power adapter being used:
 - If this is an accelerometer related issue, please include its model number here:

**Additional context**

**Comment by River-b** [comment]
could you please provide photos of the differences or a video link showing this on 2.17 
what language are you using?

**Comment by River-b** [comment]
if you could load 2.16 also and give photos of both so we can see the change in Vertical location of the icons from their previous position?

**Comment by the-remmer** [comment]
Hello, I'm not the author of the issue but I think noticed the same thing. The whole UI that is not centered. Here are some photos:

[https://imgur.com/a/YbKMp1d](https://imgur.com/a/YbKMp1d)

I'm on v2.17.923915C on a TS80P, with the TS80P_EN language pack.

**Comment by Ralim** [comment]
You appear to have a non-standard screen.

The standard screen is a 96*16 WHITE OLED module.

**Comment by Ralim** [comment]
I'm not sure what screen has been fitted to yours  it may use slightly different pixel offsets I'm guessing.

Can you share that test bootup logo and I'll test it out here, could still be a bug

**Comment by the-remmer** [comment]
> Can you share that test bootup logo

Here it is: [https://i.imgur.com/SrgD8I1.png](https://i.imgur.com/SrgD8I1.png)

**Comment by River-b** [comment]
are these official miniware soldering irons or  Clones/fake copies?

**Comment by discip** [comment]
@NiklasVoigt
Could you please confirm, if your display looks similar to the one @the-remmer posted pictures of?

@the-remmer
This is due to the way this OLED display is built!

See the difference in the length of the green bars I put there?
Actually if you happen to have a microscope at hand, you will be able to observe the number of the actual pixels or at least see if there are any unilluminated pixels below the test image.

- If you align the physical body of the display exactly in the center of the PCB, the illuminated part of it will be shifted upwards.

  So if you want it to be vertically centered , you will have to open up your device see here (https://github.com/Ralim/IronOS/issues/630#issuecomment-809748658) and **try** to shift the display down a bit (You could use the measurements provided in the picture / pdf to figure out by which amount.).
But I doubt this will work, since the ribbon cable is pretty short.

This applies to all the miniware devices (**TS100**, **TS80**[**P**], **MHP30**), since they all come with this kind of display.

So nothing new I guess. Except for the color of the pixels. There are 3 to choose from out there *(white, sky blue & yellow)*.

![WEO009616A](https://user-images.githubusercontent.com/53649486/159574771-f9151b85-a2f7-47b0-9fb3-cd23aa30f96a.jpg)
[WEO009616A.pdf](https://crystage.com/pdf/OLED/goled/WEO009616A.pdf)

So this can be closed right? 😊

**Comment by the-remmer** [comment]
> are these official miniware soldering irons or Clones/fake copies?

It's probably a clone, I got it from AliExpress.

@discip thanks for the info, you are right I checked with a magnifier and it's the active area itself that is not centered.

I'm sorry, I wanted to be helpful but I realize now that it was probably not the same thing that the original issue author had encountered.

**Comment by discip** [comment]
@Ralim 
Seems that the OP is not interested anymore.
Please close this issue. 😊

thanks
