### ISSUE TITLE
Change the order of charging protocols (PD <-> QC)

### ISSUE THREAD

**Issue by D33pWat3r** [Ralim/IronOS#1323]
The charging stations that I use support different protocols (QC2,QC3,PD2,PD3,..) via the USB-C interface.
For my TS80P, I prefer to use QC3 with up to 14V. PD2 can offer only 9V & 12V (the other voltages are too high).

So far, when I need a little more power, I use a USB-A to USB-C cable to eliminate the CC line.
But actually, I would always like to use my heat-resistant USB-C to USB-C cable.

Could you create a selection in the menu where you can switch between the order between PD and QC?

**Comment by Ralim** [comment]
Set the PD timeout to 0 and it will skip PD negotiation.

This order is because a compliant PD charger will not support QC, and also it will only send its capabilities message for a short duration. This duration is less than the minimum time to enter QC.

Also some non-compliant chargers that do PD and QC, as soon as you try for QC they disable PD on you.

**Comment by discip** [comment]
@D33pWat3r
Did you try what @Ralim suggested to do and if so, did it solve your issue?
If it did please do not to forget to close this issue. 😊

thanks
