### ISSUE TITLE
Pinecil V2: losing connection with tip, temps going crazy

### ISSUE THREAD

**Issue by genesi5** [Ralim/IronOS#1768]
Hello there!

I've been using Pinecil V2 for several weeks, and one day it didn't want to turn on, both with PD and DC barrel. I was looking the troubleshoot in web and one of the reasons (which appeared to be true) was FUSB302MPX PD controller, so i desoldered it with solder fan. It helped, iron started working, since i use DC barrel for the most part, so, lack of PD feed doesn't really bother me.

But then i noticed something strange. 

When i turn on my iron, on idle state (i.e. not heated up), it loses connection with tip about every 10-15 seconds, and idle temp goes higher than it supposed to be. When i heat the tip up, it also going crazy, peaking up to ~477°C for a short moment.

https://github.com/Ralim/IronOS/assets/25093320/785a4adc-0854-42ab-8910-c46185b425ad

What could it be? Tip? Hardware? Firmware?

**What i am running:**
* **Device**: Pinecil V2
* **Firmware**: 2.21.5D96470
* **Tip**: stock TS-B2
* **Power supply**: have two of them:
  * LED power supply, 24V, 6.25A (150W), (23,1V on input, according to device GUI) 
  * another LED power supply, 12V, 12.5A (150W), (11,6V on input, according to device GUI)

**Comment by Ralim** [comment]
So that looks awfully like either a bad PSU (bad regulation/poorly designed current limiting) causing resets or damage to the device. Or it could be that when the tip pulse runs to keep the PSU awake (as its not PD), something is browning out and resetting.

My first suspicion would be power supply related either them not being well regulated or they have spiked in the past and damaged something. Do you have any information on the supplies used? Normally LED power supplies are quite shockingly bad at regulation as they are designed to run in CC mode.

**Comment by genesi5** [comment]
After some empiric research and number of dead FUSB302MPX chips, I'd came to a point that those spikes are happening when this controller is not in a place (as I said in issue starter, had to remove it since, it doesn't allow iron to boot, when damaged), since it's kinda sensitive and easily damaged under some conditions. Maybe because of accidental unplugging while operating, since the DIY barrel I have is only 9mm long and doesn't have stiff spring inside. 
Btw, is it safer to unplug after heating mode is off (hold '-'), or it doesn't really matter?

>My first suspicion would be power supply related either them not being well regulated or they have spiked in the past and damaged something

I also have 19V laptop AC adapter from ASUS laptop (with DC 5525, but it's elbow connector, which is not convenient, otherwise I wouldn't mess with external PSU). I guess, it should have some basic protections, but the same thing happening. So, I guess, it's more about the Pinecil design.

Speaking of PSU, the 24v one said to be having protections from short circuit, overheating, overloading and power surges, and as it self-described - meant not only for LED. And PCB design looks kinda promising (unlike 12V one, which was bought primarily for LED and was used only twice with iron to check whether it able to solder). Unfortunately, I can't really provide any datasheet on 24V PSU, only photo 😢. All i can say it is produced by **General Lighting Systems**, and there is a marking `HH-CT200W-REV1.3C`, but I wasn't able to find anything on that.

![IMG_20230825_111339](https://github.com/Ralim/IronOS/assets/25093320/31eed1d8-e570-4c00-a2d4-446cd176c56d)

**Comment by Ralim** [comment]
Sorry for not getting back to this until now, life is busy on and off.

>Btw, is it safer to unplug after heating mode is off (hold '-'), or it doesn't really matter?
On well regulated supplies it doesn't really matter. For led (constant current control loop) much better to stop. Just as these tend to be focused on tight current control rather than voltage control. And these soldering irons are not kind to current control as they basically slam between no current and full current at 5/10hz which is very much _unlike_ a LED.
This is why i generally advise not using them. Not because they are bad but because we are the opposite of what they are designed for.

The FUSB302 is only connected to the CC pins in the USB-C port in the v2 units (no connection to VBus). So I wouldn't expect issues to arise with it when using the DC jack. Only way for DC jack noise to get to it is through the main DC/DC regulator. Which if the noise is strong enough to be exceeding the rejection of the DC/DC and getting through I would be concerned how rough the incoming data is for the rest of the device.

No chance you have a scope around 🤣 
Otherwise multimetering in AC mode on the dc output should ballpark the ripple (can test under load and at idle). Should normally only see a few mV on a clean supply off the top of my head on my units here. But unsure.

That LED driver does look _well build_. So I'm a little surprised.

**Comment by genesi5** [comment]
> Sorry for not getting back to this until now, life is busy on and off.
It's ok, especially since it's not a problem anymore after i got two 65W GaN adapters by Baseus and powerbank with PD support, which is totally fine and i didn't have any problems since then (although, previous spikes could probably caused display malfunction, but since it is the same as TS101 - easy to find and replace)

I guess it's mostly my bad that i plugged iron to questionable power source with handcrafted plug, so it went not good for PD controller.
