### ISSUE TITLE
Include option to have custom idle screen

### ISSUE THREAD

**Issue by Journesaladbar** [Ralim/IronOS#190]
First off thank you so much for sharing your version of this firmware. 
The first thing I did was work on custom boot-up logos inspired by retro games to use on my Ts100.
![pacman](https://user-images.githubusercontent.com/3686811/34638743-afd4ddb6-f297-11e7-83b2-99a5c2690134.png)
Now I played with multiple logos and would love support for a custom idle screen. Maybe add functionality for the logo editor to create an idle screen specific dfu file? and support for short gifs through the editor to create custom bootup/idle animations? 
here is my potential idle screen 
![press start galiga](https://user-images.githubusercontent.com/3686811/34638759-0929230e-f298-11e7-93c6-da99335e1324.png)
Lastly, the warning message functionality should be extended. If the tip is hot and the message has been dismissed already, then scroll the idle screen to a warning message (maybe the same one) repeating every configured amount of seconds and disable the screen timeout until the tip has cooled. 
Again, thank you for this version of the firmware because it is pretty feature rich!

**Comment by Ralim** [comment]
Good ideas!

Custom idle screens should definitely be an option to add in the next release :)
Should be able to pack them in with the bootup logo to save space. I will need to think on how to do this nicely in the creation tools though.

Gifs are a bit harder, just because it adds a lot more complexity to the system and requires storing a larger number of frames for the animation. So that might be a future expansion.

That would be a good idea to add to future builds, the warning would probably be appreciated if you forget you have dismissed it.

**Comment by Ralim** [comment]
This could be packed into the changes that can come with #292.

**Comment by discip** [comment]
@Journesaladbar
Does the latest release satisfy your request?
If so, please consider closing this issue. 😊

thanks

**Comment by River-Mochi** [comment]
I don't see option to have custom Idle screens.  only to have custom boot logos on bootup.
when my Pinecil V1 goes to sleep  it says "sleeping"

not sure how I  would go about changing the idle  screen to custom based on the tools we have.

**Comment by Ralim** [comment]
The only way to change it would be to change the code.
We could have an option to show the bootup logo instead when its asleep; but its preferrable to keep the OLED off to avoid burn in imho.

**Comment by River-Mochi** [comment]
> but its preferrable to keep the OLED off to avoid burn in imho.

Ageed.  I like that OLED goes to black screen and then wakes up when i pick it up.  It's about $5 with shipping everytime you need to change your OLED screen. depending on brightness picked, how often you use the screen,  I've seen it as low as  1 year for some people but others have it 3 years no issues.

this doesn't look like a good idea,  since you mentioned wanting a  balanced option to  let the screen rest during idle so that the OLED doesn't burn out faster, perhaps this ticket should be **closed**.  Note it's from 2018  and **5 year  old ticket.**

**Comment by discip** [comment]
> but its preferrable to keep the OLED off to avoid burn in imho.

Due to the weight of this statement, I am closing this issue.
