### ISSUE TITLE
TS100  Thermal Runaway Retune/Option to disable

### ISSUE THREAD

**Issue by Tekz42** [Ralim/IronOS#1946]
**Is your feature request related to a problem? Please describe.**
TS100 going into thermal runaway constantly while soldering with low voltage power sources i.e. 3s LiPo. This makes soldering in the field a headache as Iron is constantly going into cooldown causing joints to be half soldered.

**Describe the solution you'd like**
Retune of Thermal Runaway or Option to disable Thermal Runaway.

**Describe alternatives you've considered**
Buy higher voltage power sources.

**Additional context**
N/A

**Comment by Eheran1** [comment]
I have previously reported this issue with my TS80. If you work on something that takes time to heat up and then stabilizes on some temperature, the TS80 goes into runaway mode. Please add a some test before triggering this mode: Turn down heating a bit (say 50%) and see if the temperature drops. AFAIK this should not be the case with an actual runaway, where the temperature sensing itself is broken? So it would not decrease in that case. But not sure if I understand the mechanics behind a runaway correctly.

**Comment by Ralim** [comment]
I've had a crack at a different style of detector.
Could you try these builds? https://github.com/Ralim/IronOS/actions/runs/12209178967
@Eheran1  / @Tekz42

**Comment by Eheran1** [comment]
Sorry, not sure what to do with your link. Really not a Github expert. How should I proceed to test it?

**Comment by discip** [comment]
Please use this link:
https://github.com/Ralim/IronOS/actions/runs/12209178967/artifacts/2287845061

**Comment by Eheran1** [comment]
404 not found.

-------- Original message --------
From: discip ***@***.***>
Date: 07/12/2024 20:19 (GMT+01:00)
To: Ralim/IronOS ***@***.***>
Cc: Eheran1 ***@***.***>, Mention ***@***.***>
Subject: Re: [Ralim/IronOS] TS100 Thermal Runaway Retune/Option to disable (Issue #1946)


Please use this link:
https://github.com/Ralim/IronOS/actions/runs/12209178967/artifacts/2287845061

**Comment by bamdadkhan** [comment]
hi, although i'm not the OP, i was able to download the artifact, but only after logging in.

i can also confirm that the 'thermal runaway' situation seems to be fixed, at least on my TS80.

thank you < 3

**Comment by Eheran1** [comment]
I have no way to test it right now, but could you point me to the function(s) that does the test/finds the runaway? I would like to look at it. Also, I could try to feed it some data that looks like what I remember.

**Comment by Ralim** [comment]
@Eheran1 You can see the changes here https://github.com/Ralim/IronOS/pull/2012/files

**Comment by Eheran1** [comment]
Ah thank you. So the essence is:
-  Always update lowest tip temperature seen
- Only update highest tip temperature seen when currently heating
- If we have been heating for longer than "THERMAL_RUNAWAY_TIME_SEC" (now 20, previous 45)
- And if the highest tip temperature seen is larger than the minimum (should always be the case?)
- Then if the dT is smaller than "THERMAL_RUNAWAY_TEMP_C" (now set to 3 instead of previous 10 for various devices) we get the thermal runaway.
The core change seems to be the different threshold of less than 3 °C of change needed to signal a runaway condition. How much does the temperature fluctuate during a runaway condition? This would still trigger if the temperature is not changing much, like due to high thermal mass compared to heating power. I would much prefer an active test as a "second stage" that turns the heater off (or lower) for a second or so to check if that does anything. If it does cause a substantial cooling, then do not trigger the test again for something like 10 minutes.

```

  if (currentTipTempInC < tiptempMin) {
    tiptempMin = currentTipTempInC;
  }

  if (thisCycleIsHeating && currentTipTempInC > tipTempMax) {
    tipTempMax = currentTipTempInC;
  }
  
    if ((xTaskGetTickCount() - heatCycleStart) > (THERMAL_RUNAWAY_TIME_SEC * TICKS_SECOND)) {
    if (tipTempMax > tiptempMin) {
      // Have been heating for min seconds, check if the delta is large enough
      TemperatureType_t delta = tipTempMax - tiptempMin;
      haveSeenDelta           = true;

      if (delta < THERMAL_RUNAWAY_TEMP_C) {
        heaterThermalRunaway = true;
      }
    }
  } else {
    tipTempCRunawayTemp   = currentTipTempInC;
    runawaylastChangeTime = xTaskGetTickCount();
  }
```

**Comment by Eheran1** [comment]
Ah thank you. So the essence is:

- Always update lowest tip temperature seen
- Only update highest tip temperature seen when currently heating
- If we have been heating for longer than "THERMAL_RUNAWAY_TIME_SEC" (now 20, previous 45)
- And if the highest tip temperature seen is larger than the minimum (when is this not the case?)
- Then if the dT is smaller than "THERMAL_RUNAWAY_TEMP_C" (now set to 3 instead of previous 10 for various devices) we get the thermal runaway.

The core change seems to be the different threshold of less than 3 °C of change needed to signal a runaway condition. How much does the temperature fluctuate during a runaway condition? This would still trigger if the temperature is not changing much, like due to high thermal mass compared to heating power. I would prefer an additional test as a "second stage" after this initial test. It should turn the heater off (or lower) for a second or so (depending on the dynamics of the system, I assume 1 s is enough for a significant cool down) to check if that does anything. If it does cause a substantial cooling, then do not trigger the test again for something like 10 minutes. While the short cooling is perhaps still annoying: It is only once, very short, and automatically stops without looking at the display and/or pressing something.

Relevant code:
```
  if (currentTipTempInC < tiptempMin) {
    tiptempMin = currentTipTempInC;
  }

  if (thisCycleIsHeating && currentTipTempInC > tipTempMax) {
    tipTempMax = currentTipTempInC;
  }
  
    if ((xTaskGetTickCount() - heatCycleStart) > (THERMAL_RUNAWAY_TIME_SEC * TICKS_SECOND)) {
    if (tipTempMax > tiptempMin) {
      // Have been heating for min seconds, check if the delta is large enough
      TemperatureType_t delta = tipTempMax - tiptempMin;
      haveSeenDelta           = true;

      if (delta < THERMAL_RUNAWAY_TEMP_C) {
        heaterThermalRunaway = true;
      }
    }
```

**Comment by discip** [comment]
@Eheran1
If you need to edit a post, you can do so at any time by clicking on the 3 dots in the top right corner of the post and selecting **`Edit`**.
Just so you don't have to repost everything multiple times. 😊

**Comment by Tekz42** [comment]
@Ralim Sorry for the extremely late reply, life has been busy elsewhere. Thankfully the retune has solved the issue as of late. Im still to put more time in but it's looking promising. Thank you so much.

**Comment by Ralim** [comment]
@Tekz42 No problem, late feedback is better than none. Glad to hear its helping.
